#!/bin/sh
currentdir=$(pwd)
destdir=${WEBHACC_DIR-./local/webhacc}
git clone https://github.com/manakai/webhacc-cli ${destdir}
cd ${destdir} && make deps && \
cd ${currentdir} && cp ${destdir}/webhacc ./webhacc
